### ISSUE TITLE
Previous Hash URL?

### ISSUE THREAD

**Issue by lauthiamkok** [millermedeiros/crossroads.js#119]
How can I get the previous hash url?

for instance, my previous url is `http://mysite/#/home/`, this this current requested url `http://mysite/#/about/`

I can get the current one in the method below, but what about the previous one?

```
       crossroads.addRoute('{module}/{type}/{branch}/', function(module, type, branch){ 
            
            console.log(document.referrer); // I get null.
            
        });
```

**Comment by millermedeiros** [comment]
I did not add any option for that since you can create your own `history` handler using the [`routed` signal](http://millermedeiros.github.io/crossroads.js/#crossroads-routed):

```js
var prevHash = '';

crossroads.routed.add(function(request, data) {
  prevHash = request;
});
```

sorry for the huge delay but I had a lot of notifications on github and my email notifications was disabled.
