### ISSUE TITLE
Remove hashtag for frontend clients

### ISSUE THREAD

**Issue by martinsookael** [millermedeiros/crossroads.js#126]
Thank you for building Crossroads.
I looked long and wide for a proper routing for  Single Page Apps and so far Crossroads has been exactly what it promises.  

I'm using it with: 
https://github.com/jayJs/jay 
and
https://github.com/jayJs/node-jay

Signals and Hasher are also involved.

Question: 
Current url: "www.domain.com/#/post/first-post"
How I'd like it to be: "www.domain.com/post/first-post"

What's the best strategy for achieving this?

**Comment by millermedeiros** [comment]
you would need to listen to `popstate` and use `pushState` to set the URL instead of `location.hash`. see MDN documentation about the History API: https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history
