### ISSUE TITLE
What would be a good strategy for SEO and the use of crossroads.js?

### ISSUE THREAD

**Issue by robertleeplummerjr** [millermedeiros/crossroads.js#129]
I think this may be one of the biggest things holding many back from going all in with libraries like crossroads.js. But I must say... I'm sold, and I am LOVING IT!

Thanks again!

**Comment by millermedeiros** [comment]
good strategy is rendering your pages on the server side whenever possible and/or having static fallback, see: https://developers.google.com/webmasters/ajax-crawling/

**Comment by robertleeplummerjr** [comment]
I also found this as a free service: http://prerender.io
It supports the hashes ( https://prerender.io/documentation ), so either way, we now have an means to an end.
