### ISSUE TITLE
Support of native URLs

### ISSUE THREAD

**Issue by olignyf** [millermedeiros/crossroads.js#151]
Hi,
Following the documentation I setup crossroads in my project and I see it only works with hashes # and not raw URL changes. Is this a limitation or just something I missed ?
Thanks

**Comment by sumitkm** [comment]
Hi Francois,

You can use HistoryJS in conjunction with Crossroads to use non-hash
urls, but this only works in browser that fully support pushstate
(read > IE9...)

You can find an example of how to do this here

https://github.com/millermedeiros/crossroads.js/wiki/Examples#using-with-historyjs

Let us know if this helps,
Cheers

## 

  Sumit Kumar Maitra
  code@sumitmaitra.com

**Comment by olignyf** [comment]
Thanks ! Yes it helps.
I have another question. I hope you don't mind if I open another ticket. At least if other persons come across the same question they will be able to find the answer by googling.
